### ISSUE TITLE
Install through Composer

### ISSUE THREAD

**Issue by shtrih** [jayhealey/Webception#36]
Webception requires `symfony/yaml` version 2.5.*, but in Codeception it's v2.6.4. So I got an error:
![_002](https://cloud.githubusercontent.com/assets/544063/6480768/52ba44b6-c268-11e4-9bb3-d29ddfeeead2.png)

**Comment by elchesco** [comment]
works for me, here's my composer.json

{
    "name": "jayhealey/webception",
    "description": "Web Interface for running Codeception tests.",
    "keywords": ["codeception", "webception", "testing", "php", "web interface"],
    "homepage" : "https://github.com/jayhealey/Webception",
    "authors": [
        {
            "name": "James Healey",
            "email": "jayhealey@gmail.com",
            "homepage": "http://twitter.com/jayhealey",
            "role": "Developer"
        }
    ],
    "license": "MIT",
    "require": {
        "php": ">=5.3.0",
        "slim/slim": "2.*",
        "slim/views": "0.1.*",
        "twig/twig": "~1.13",
        "symfony/yaml": "~2.6",
        "codeception/codeception": "*",
        "guzzlehttp/guzzle": "~5.0",
        "monolog/monolog": "~1.11",
        "fzaninotto/faker": "~1.4",
        "goodby/csv": "~1.1",
        "codeception/notifier": "dev-master"
    },
    "autoload": {
        "psr-0": {
            "App": ""
        }
    }
}

**Comment by shtrih** [comment]
I misunderstood and tried to install Webception in the project, which is pre-installed Codeception. And when I set webception in a separate project and it worked.

**Comment by elchesco** [comment]
:+1:
