### ISSUE TITLE
CodeceptionClassTestsTest::testCodeceptionCommandPath fails under Windows

### ISSUE THREAD

**Issue by Bering** [jayhealey/Webception#38]
Hi,

On Windows 2008 R2 server, the testCodeceptionCommandPath unit test fails because of **--no-colors**

Here's the output of _codecept run unit_:

    1) CodeceptionClassTestsTest::testCodeceptionCommandPath
    Failed asserting that two strings are equal.
    --- Expected
    +++ Actual
    @@ @@
    -'E:\inetpub\webception\App\Tests\_config/../../../vendor/bin/codecept run --config="E:\inetpub\webception\App\Tests\_config/codeception_pass.yml" unit WebceptionTestClassTest.php 2>&1'
    +'E:\inetpub\webception\App\Tests\_config/../../../vendor/bin/codecept run --no-colors --config="E:\inetpub\webception\App\Tests\_config/codeception_pass.yml" unit WebceptionTestClassTest.php 2>&1'

    #1  E:\inetpub\webception\App\Tests\unit\CodeceptionClassTestsTest.php:115
    #2  CodeceptionClassTestsTest->testCodeceptionCommandPath

**Comment by Bering** [comment]
I know that you don't have access to a Windows machine and I don't know much about codeception nor Yii so I figured: I'll create an issue for each unit test that fails, you can send me patches, I'll run the tests on Windows and we'll weed down the bugs. Deal? :-)

**Comment by jgdovin** [comment]
This does not seem to be specific to windows server. I am working on updating Webception to latest Codeception as WebGuy classes have gone in favor of AcceptanceTester classes and a better structure, Once I finish updating the tests to work with latest Codeception I will also be sure this test is fixed.

**Comment by elchesco** [comment]
maybe on the meantime you can just remove such option if that's failing on you, should be the one on webception/App/Lib/Codeception.php, around line 320 getCommandPath func.

**Comment by jgdovin** [comment]
#39 should fix this minor issue.

**Comment by Bering** [comment]
Yep! That fixed it! Thanks!
